/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.janelia.it.workstation.gui.geometric_search;

import java.awt.BorderLayout;

import org.janelia.it.workstation.api.entity_model.management.ModelMgr;
import org.janelia.it.workstation.gui.geometric_search.admin.GeometricSearchAdminPanel;
import org.janelia.it.workstation.gui.geometric_search.search.GeometricSearchPanel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.janelia.it.workstation.gui.geometric_search//GeometricSearch//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "GeometricSearchTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "org.janelia.it.workstation.gui.geometric_search.GeometricSearchTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_GeometricSearchAction",
        preferredID = "GeometricSearchTopComponent"
)
@Messages({
    "CTL_GeometricSearchAction=Geometric Search",
    "CTL_GeometricSearchTopComponent=Geometric Search",
    "HINT_GeometricSearchTopComponent=This is a Geometric Search window"
})
public final class GeometricSearchTopComponent extends TopComponent {

    private Logger logger = LoggerFactory.getLogger(GeometricSearchTopComponent.class);


    GeometricSearchAdminPanel adminPanel;
    GeometricSearchPanel searchPanel;

    public GeometricSearchTopComponent() {
        logger.info("GeometricSearchTopComponent()");
        initComponents();
        adminPanel=new GeometricSearchAdminPanel();
        setName(Bundle.CTL_GeometricSearchTopComponent());
        setToolTipText(Bundle.HINT_GeometricSearchTopComponent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        geometricSearchTabPane = new javax.swing.JTabbedPane();
        searchTabPanel = new javax.swing.JPanel();
        adminTabPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1200, 900));

        searchTabPanel.setPreferredSize(new java.awt.Dimension(1200, 900));

        javax.swing.GroupLayout searchTabPanelLayout = new javax.swing.GroupLayout(searchTabPanel);
        searchTabPanel.setLayout(searchTabPanelLayout);
        searchTabPanelLayout.setHorizontalGroup(
            searchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 823, Short.MAX_VALUE)
        );
        searchTabPanelLayout.setVerticalGroup(
            searchTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        geometricSearchTabPane.addTab(org.openide.util.NbBundle.getMessage(GeometricSearchTopComponent.class, "GeometricSearchTopComponent.searchTabPanel.TabConstraints.tabTitle"), searchTabPanel); // NOI18N

        javax.swing.GroupLayout adminTabPanelLayout = new javax.swing.GroupLayout(adminTabPanel);
        adminTabPanel.setLayout(adminTabPanelLayout);
        adminTabPanelLayout.setHorizontalGroup(
            adminTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 823, Short.MAX_VALUE)
        );
        adminTabPanelLayout.setVerticalGroup(
            adminTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        geometricSearchTabPane.addTab(org.openide.util.NbBundle.getMessage(GeometricSearchTopComponent.class, "GeometricSearchTopComponent.adminTabPanel.TabConstraints.tabTitle"), adminTabPanel); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(geometricSearchTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(geometricSearchTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        geometricSearchTabPane.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(GeometricSearchTopComponent.class, "GeometricSearchTopComponent.geometricSearchTabPane.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminTabPanel;
    private javax.swing.JTabbedPane geometricSearchTabPane;
    private javax.swing.JPanel searchTabPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        logger.info("componentOpened()");
        ModelMgr.getModelMgr().registerOnEventBus(this);
        initMyComponents();
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    private void initMyComponents() {
        initAdmin();
        initSearch();
    }

    private void initAdmin() {
        adminTabPanel.setLayout( new BorderLayout() );
        adminPanel=new GeometricSearchAdminPanel();
        adminTabPanel.add( adminPanel, BorderLayout.CENTER );
    }

    private void initSearch() {
        logger.info("initSearch()");
        searchTabPanel.setLayout( new BorderLayout() );
        searchPanel=new GeometricSearchPanel();
        searchTabPanel.add( searchPanel, BorderLayout.CENTER );
        searchPanel.setVisible(true);
        searchPanel.displayReady();
    }

}
