package org.janelia.jacs2.model.jacsservice;

public enum JacsServiceState {
    CREATED, SUBMITTED, QUEUED, RUNNING, WAITING, PROCESSING_COMPLETED, PROCESSING_ERROR, CANCELED, TIMEOUT, ERROR, SUCCESSFUL
}
