//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.21 at 02:53:48 PM EDT 
//


package org.janelia.it.jacs.server.ie.jaxb;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for publicationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="publicationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pubDate" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="publicationAccession" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="journal" type="{}journalEntryType" minOccurs="0"/>
 *         &lt;element name="full_text" type="{}locationType" minOccurs="0"/>
 *         &lt;element name="supplemental_text" type="{}locationType" minOccurs="0"/>
 *         &lt;element name="summary" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="projects" type="{}projectsType"/>
 *         &lt;element name="authors" type="{}authorsType"/>
 *         &lt;element name="dataFile" type="{}dataFileType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="hierarchyNode" type="{}hierarchyNodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="abstractOfPublication" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="objectId" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "publicationType", propOrder = {
    "title",
    "pubDate",
    "publicationAccession",
    "journal",
    "fullText",
    "supplementalText",
    "summary",
    "projects",
    "authors",
    "dataFile",
    "hierarchyNode",
    "abstractOfPublication",
    "description"
})
public class PublicationType {

    @XmlElement(required = true)
    protected String title;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    protected Date pubDate;
    @XmlElement(required = true)
    protected String publicationAccession;
    protected JournalEntryType journal;
    @XmlElement(name = "full_text")
    protected LocationType fullText;
    @XmlElement(name = "supplemental_text")
    protected LocationType supplementalText;
    protected String summary;
    @XmlElement(required = true)
    protected ProjectsType projects;
    @XmlElement(required = true)
    protected AuthorsType authors;
    protected List<DataFileType> dataFile;
    protected List<HierarchyNodeType> hierarchyNode;
    protected String abstractOfPublication;
    protected String description;
    @XmlAttribute
    protected Long objectId;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the pubDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getPubDate() {
        return pubDate;
    }

    /**
     * Sets the value of the pubDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubDate(Date value) {
        this.pubDate = value;
    }

    /**
     * Gets the value of the publicationAccession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicationAccession() {
        return publicationAccession;
    }

    /**
     * Sets the value of the publicationAccession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicationAccession(String value) {
        this.publicationAccession = value;
    }

    /**
     * Gets the value of the journal property.
     * 
     * @return
     *     possible object is
     *     {@link JournalEntryType }
     *     
     */
    public JournalEntryType getJournal() {
        return journal;
    }

    /**
     * Sets the value of the journal property.
     * 
     * @param value
     *     allowed object is
     *     {@link JournalEntryType }
     *     
     */
    public void setJournal(JournalEntryType value) {
        this.journal = value;
    }

    /**
     * Gets the value of the fullText property.
     * 
     * @return
     *     possible object is
     *     {@link LocationType }
     *     
     */
    public LocationType getFullText() {
        return fullText;
    }

    /**
     * Sets the value of the fullText property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationType }
     *     
     */
    public void setFullText(LocationType value) {
        this.fullText = value;
    }

    /**
     * Gets the value of the supplementalText property.
     * 
     * @return
     *     possible object is
     *     {@link LocationType }
     *     
     */
    public LocationType getSupplementalText() {
        return supplementalText;
    }

    /**
     * Sets the value of the supplementalText property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationType }
     *     
     */
    public void setSupplementalText(LocationType value) {
        this.supplementalText = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummary(String value) {
        this.summary = value;
    }

    /**
     * Gets the value of the projects property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectsType }
     *     
     */
    public ProjectsType getProjects() {
        return projects;
    }

    /**
     * Sets the value of the projects property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectsType }
     *     
     */
    public void setProjects(ProjectsType value) {
        this.projects = value;
    }

    /**
     * Gets the value of the authors property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorsType }
     *     
     */
    public AuthorsType getAuthors() {
        return authors;
    }

    /**
     * Sets the value of the authors property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorsType }
     *     
     */
    public void setAuthors(AuthorsType value) {
        this.authors = value;
    }

    /**
     * Gets the value of the dataFile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataFile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataFile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataFileType }
     * 
     * 
     */
    public List<DataFileType> getDataFile() {
        if (dataFile == null) {
            dataFile = new ArrayList<DataFileType>();
        }
        return this.dataFile;
    }

    /**
     * Gets the value of the hierarchyNode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hierarchyNode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHierarchyNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HierarchyNodeType }
     * 
     * 
     */
    public List<HierarchyNodeType> getHierarchyNode() {
        if (hierarchyNode == null) {
            hierarchyNode = new ArrayList<HierarchyNodeType>();
        }
        return this.hierarchyNode;
    }

    /**
     * Gets the value of the abstractOfPublication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbstractOfPublication() {
        return abstractOfPublication;
    }

    /**
     * Sets the value of the abstractOfPublication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbstractOfPublication(String value) {
        this.abstractOfPublication = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the objectId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getObjectId() {
        return objectId;
    }

    /**
     * Sets the value of the objectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setObjectId(Long value) {
        this.objectId = value;
    }

}
