package org.janelia.it.workstation.gui.large_volume_viewer.options;

import java.awt.BorderLayout;

import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import org.openide.util.NbPreferences;

import net.miginfocom.swing.MigLayout;

public class ApplicationPanel extends javax.swing.JPanel {

    public static final String PREFERENCE_LOAD_LAST_OBJECT = "LoadLastObject";
    public static final String PREFERENCE_LOAD_LAST_OBJECT_DEFAULT = "true";
    
    private final ApplicationOptionsPanelController controller;
    private JCheckBox loadLastCheckbox; 
    
    ApplicationPanel(final ApplicationOptionsPanelController controller) {
        this.controller = controller;
        initComponents();

        JPanel attrPanel = new JPanel(new MigLayout("wrap 2, ins 20", "[grow 0, growprio 0][grow 100, growprio 100]"));

        this.loadLastCheckbox = new JCheckBox();
        loadLastCheckbox.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                controller.changed();
            }
        });
        JLabel titleLabel = new JLabel("Load last opened sample or workspace on startup: ");
        titleLabel.setLabelFor(loadLastCheckbox);
        attrPanel.add(titleLabel,"gap para");
        attrPanel.add(loadLastCheckbox,"gap para, width 100:400:600, growx");
        
        add(attrPanel, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        String loadLastStr = NbPreferences.forModule(ApplicationPanel.class).get(PREFERENCE_LOAD_LAST_OBJECT, PREFERENCE_LOAD_LAST_OBJECT_DEFAULT);
        loadLastCheckbox.setSelected(Boolean.parseBoolean(loadLastStr));
    }

    void store() {
        NbPreferences.forModule(ApplicationPanel.class).put(PREFERENCE_LOAD_LAST_OBJECT, loadLastCheckbox.isSelected()+"");
    }

    boolean valid() {
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
