package org.janelia.it.workstation.gui.split_picking;

import java.awt.BorderLayout;
import java.util.Properties;
import java.util.concurrent.Callable;

import org.janelia.it.workstation.gui.framework.console.ViewerManager;
import org.janelia.it.workstation.gui.framework.viewer.IconDemoPanel;
import org.janelia.it.workstation.gui.framework.viewer.ViewerSplitPanel;
import org.janelia.it.workstation.model.entity.RootedEntity;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

import javax.swing.GroupLayout;
import javax.swing.JPanel;
import org.janelia.it.workstation.gui.util.WindowLocator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Top component showing dual AD/DBD split picking views.
 */
@ConvertAsProperties(
        dtd = "-//org.janelia.it.workstation.gui.split_picking//SplitPickingLanes//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = SplitPickingLanesTopComponent.PREFERRED_ID,
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false, position = 200)
@Messages({
    "CTL_SplitPickingLanesAction=Split Picking Lanes",
    "CTL_SplitPickingLanesTopComponent=Split Picking Tool",
    "HINT_SplitPickingLanesTopComponent=Choose one image from each lane"
})
public final class SplitPickingLanesTopComponent extends TopComponent {
    
    private Logger log = LoggerFactory.getLogger(SplitPickingLanesTopComponent.class);
    
    public static final String PREFERRED_ID = "SplitPickingLanesTopComponent";

    private final ViewerManager viewerManager;
    
    public SplitPickingLanesTopComponent() {
        initComponents();
        setName(Bundle.CTL_SplitPickingLanesTopComponent());
        setToolTipText(Bundle.HINT_SplitPickingLanesTopComponent());
        viewerManager = new ViewerManager();
    }
    
    private void initMyComponents() {
        jPanel1.add( viewerManager.getViewerContainer(), BorderLayout.CENTER );
    }
    
    public IconDemoPanel getMainPanel() {
        return (IconDemoPanel)viewerManager.getMainViewer(IconDemoPanel.class);
    }
    
    public IconDemoPanel getSecondaryPanel() {
        return (IconDemoPanel)viewerManager.getSecViewer(IconDemoPanel.class);
    }
    
    public void showEntityInMainViewer( RootedEntity entity ) {
        viewerManager.showEntityInMainViewer( entity );
    }
    
    public void showEntityInSecViewer( RootedEntity entity ) {
        viewerManager.showEntityInSecViewer( entity );
    }
    
    public void showEntityInMainViewer( RootedEntity entity, Callable callable ) {
        viewerManager.showEntityInMainViewer( entity, callable );
    }
    
    public void showEntityInSecViewer( RootedEntity entity, Callable callable ) {
        viewerManager.showEntityInSecViewer( entity, callable );
    }
    
    public ViewerSplitPanel getViewerSplitPanel() {
        return viewerManager.getViewerContainer();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();

        jPanel1.setLayout(new BorderLayout());

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        initMyComponents();
    }

    @Override
    public void componentClosed() {
        TopComponent tc = WindowLocator.getByName(SplitPickingTopComponent.PREFERRED_ID);
         if (tc!=null) tc.close();
    }

    void writeProperties(Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
