/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.janelia.it.workstation.gui.stack_viewer.top_component;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import org.janelia.it.workstation.gui.stack_viewer.gui.Mip3dStackViewer;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.janelia.it.workstation.gui.stack_viewer.top_component//StackViewer//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "StackViewerTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "org.janelia.it.workstation.gui.stack_viewer.top_component.StackViewerTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_StackViewerAction",
        preferredID = "StackViewerTopComponent"
)
@Messages({
    "CTL_StackViewerAction=StackViewer",
    "CTL_StackViewerTopComponent=Stack Viewer",
    "HINT_StackViewerTopComponent=Browse to View Stacks of Various Formats in 3D"
})
public final class StackViewerTopComponent extends TopComponent {
    
    private Mip3dStackViewer stackViewer;

    public StackViewerTopComponent() {
        initComponents();
        setName(Bundle.CTL_StackViewerTopComponent());
        setToolTipText(Bundle.HINT_StackViewerTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();

        setDisplayName(org.openide.util.NbBundle.getMessage(StackViewerTopComponent.class, "StackViewerTopComponent.displayName")); // NOI18N
        setLayout(new java.awt.BorderLayout());

        contentPanel.setLayout(new java.awt.BorderLayout());
        add(contentPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // We want input for a file name.
        final JButton fileOpenButton = new JButton("Browse and Open Stack");
        contentPanel.add(new JLabel(""), BorderLayout.CENTER); // Placeholder.
        contentPanel.add(fileOpenButton, BorderLayout.SOUTH);
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
            }
        });
        fileOpenButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        JFileChooser jfc = new JFileChooser();
                        int option = jfc.showOpenDialog(StackViewerTopComponent.this);
                        if (option == JFileChooser.APPROVE_OPTION) {
                            stackViewer = new Mip3dStackViewer();
                            stackViewer.launch(jfc.getSelectedFile().getAbsolutePath());
                        }
                    }
                });
            }
        });
    }

    @Override
    public void componentClosed() {
        if (stackViewer != null)
            stackViewer.close();
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
