<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.janelia</groupId>
        <artifactId>workstation</artifactId>
        <version>9.21</version>
        <relativePath>../..</relativePath>
    </parent>

    <name>WoodstoxLib</name>
    <groupId>org.janelia.workstation</groupId>
    <artifactId>woodstoxlib</artifactId>
    <version>9.21</version>
    <packaging>nbm</packaging>

    <dependencies>
        <dependency>
            <groupId>org.codehaus.woodstox</groupId>
            <artifactId>stax2-api</artifactId>
            <version>4.2.1</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.woodstox</groupId>
            <artifactId>woodstox-core</artifactId>
            <version>6.2.7</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.netbeans.utilities</groupId>
                <artifactId>nbm-maven-plugin</artifactId>
                <configuration>
                    <publicPackages>
                        <publicPackage>com.ctc.wstx.**</publicPackage>
                        <publicPackage>org.codehaus.stax2.**</publicPackage>
                    </publicPackages>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
