package org.janelia.it.workstation.gui.top_component;

import java.awt.BorderLayout;
import java.util.Properties;
import org.janelia.it.workstation.gui.framework.console.Browser;
import org.janelia.it.workstation.gui.framework.outline.EntityDetailsOutline;

import org.janelia.it.workstation.gui.framework.session_mgr.SessionMgr;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Top component which displays the data inspector.
 */
@ConvertAsProperties(
        dtd = "-//org.janelia.it.workstation.gui.dialogs.nb//EntityDetails//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = EntityDetailsTopComponent.PREFERRED_ID,
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "appExplorerBtm", openAtStartup = false, position = 20)
@ActionID(category = "Window", id = "org.janelia.it.workstation.gui.dialogs.nb.EntityDetailsTopComponent")
@ActionReference(path = "Menu/Window", position = 401)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_EntityDetailsAction",
        preferredID = EntityDetailsTopComponent.PREFERRED_ID
)
@Messages({
    "CTL_EntityDetailsAction=Legacy Data Inspector",
    "CTL_EntityDetailsTopComponent=Legacy Data Inspector",
    "HINT_EntityDetailsTopComponent=See data details"
})
public final class EntityDetailsTopComponent extends TopComponent {

    private Logger log = LoggerFactory.getLogger( EntityDetailsTopComponent.class );
    
    public static final String PREFERRED_ID = "EntityDetailsTopComponent";
    
    public EntityDetailsTopComponent() {
        initComponents();
        setName(Bundle.CTL_EntityDetailsTopComponent());
        setToolTipText(Bundle.HINT_EntityDetailsTopComponent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void componentOpened() {
        final Browser browser = SessionMgr.getBrowser();
        if (browser == null) {
            throw new IllegalStateException("Failed to obtain browser object for component.");
        }
        final EntityDetailsOutline entityDetailsOutline = browser.getEntityDetailsOutline();
        if (entityDetailsOutline == null) {
            throw new IllegalStateException("No entity details outline located.");
        }
        else {
            log.debug("Activating entity details outline");
            entityDetailsOutline.activate();
            jPanel1.add(entityDetailsOutline, BorderLayout.CENTER);
        }
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
