package org.janelia.it.workstation.gui.top_component;

import java.util.Properties;

import javax.swing.JTextArea;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Top component which displays the data explorer. 
 */
@ConvertAsProperties(
        dtd = "-//org.janelia.it.workstation.gui.dialogs.nb//EntityExplorer//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = EntityExplorerTopComponent.PREFERRED_ID,
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = false, position = 10)
@ActionID(category = "Window", id = "org.janelia.it.workstation.gui.dialogs.nb.EntityExplorerTopComponent")
@ActionReference(path = "Menu/Window/Legacy", position = 10)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_EntityExplorerAction",
        preferredID = EntityExplorerTopComponent.PREFERRED_ID
)
@Messages({
    "CTL_EntityExplorerAction=Legacy Data Explorer",
    "CTL_EntityExplorerTopComponent=Legacy Data Explorer",
    "HINT_EntityExplorerTopComponent=Browse the data"
})
public final class EntityExplorerTopComponent extends TopComponent implements ExplorerManager.Provider {

    private Logger log = LoggerFactory.getLogger( EntityExplorerTopComponent.class );
    
    public static final String PREFERRED_ID = "EntityExplorerTopComponent";
    
    private ExplorerManager mgr = new ExplorerManager();
    
    public EntityExplorerTopComponent() {
        initComponents();
        setName(Bundle.CTL_EntityExplorerTopComponent());
        setToolTipText(Bundle.HINT_EntityExplorerTopComponent());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setLayout(new java.awt.BorderLayout());
        JTextArea area = new JTextArea("The Legacy Data Explorer is no longer available. Please use Window->Core->Data Inspector instead.");
        area.setLineWrap(true);
        area.setWrapStyleWord(true);
        add(area);
        
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void componentOpened() {
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return mgr;
    }
}
