package org.janelia.it.workstation.gui.browser.components;

import com.google.common.eventbus.Subscribe;
import java.awt.BorderLayout;
import org.janelia.it.workstation.gui.browser.gui.inspector.DomainInspectorPanel;
import org.janelia.it.workstation.gui.browser.events.Events;
import org.janelia.it.workstation.gui.browser.events.selection.DomainObjectSelectionEvent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Top component for the Data Inspector, which shows details about a single
 * domain object. 
 * 
 * @author <a href="mailto:rokickik@janelia.hhmi.org">Konrad Rokicki</a>
 */
@ConvertAsProperties(
        dtd = "-//org.janelia.it.workstation.gui.browser.components//DomainInspector//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = DomainInspectorTopComponent.TC_NAME,
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "appExplorerBtm", openAtStartup = true, position = 20)
@ActionID(category = "Window", id = "org.janelia.it.workstation.gui.browser.components.DomainInspectorTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_DomainInspectorAction",
        preferredID = DomainInspectorTopComponent.TC_NAME
)
@Messages({
    "CTL_DomainInspectorAction=Data Inspector",
    "CTL_DomainInspectorTopComponent=Data Inspector",
    "HINT_DomainInspectorTopComponent=Details about the selected domain object"
})
public final class DomainInspectorTopComponent extends TopComponent {

    private Logger log = LoggerFactory.getLogger(DomainInspectorTopComponent.class);

    public static final String TC_NAME = "DomainInspectorTopComponent";
    
    private final DomainInspectorPanel detailsPanel;

    public DomainInspectorTopComponent() {
        initComponents();
        setName(Bundle.CTL_DomainInspectorTopComponent());
        setToolTipText(Bundle.HINT_DomainInspectorTopComponent());
        this.detailsPanel = new DomainInspectorPanel();
        add(detailsPanel, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        Events.getInstance().registerOnEventBus(this);
    }

    @Override
    public void componentClosed() {
        Events.getInstance().unregisterOnEventBus(this);
    }

    @Subscribe
    public void domainObjectSelected(DomainObjectSelectionEvent event) {
        
        if (!event.isSelect()) {
            log.debug("Event is not selection: {}",event);
            return;
        }

        if (!event.isClearAll()) {
            log.debug("Event is not clear all: {}",event);
            return;
        }
        
        detailsPanel.loadDomainObject(event.getDomainObject());
    }
    
    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
