package org.janelia.it.workstation.gui.browser.components;

import javax.swing.JTextArea;

import org.janelia.it.workstation.browser.gui.support.WindowLocator;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;


/**
 * TODO: remove this in a future release, once users have reset their windows
 * 
 * @author <a href="mailto:rokickik@janelia.hhmi.org">Konrad Rokicki</a>
 */
@ConvertAsProperties(
        dtd = "-//org.janelia.it.workstation.gui.browser.components//DomainExplorer//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = DomainExplorerTopComponent.TC_NAME,
        iconBase = "images/folder.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = false, position = 500)
@ActionID(category = "Window", id = "org.janelia.it.FlyWorkstation.gui.dialogs.nb.DomainExplorerTopComponent")
@ActionReference(path = "Menu/Window/Legacy", position = 1)
@TopComponent.OpenActionRegistration(   
        displayName = "#CTL_LegacyDomainExplorerAction",
        preferredID = DomainExplorerTopComponent.TC_NAME
)
@Messages({
    "CTL_LegacyDomainExplorerAction=Legacy View",
    "CTL_LegacyDomainExplorerTopComponent=Legacy View"
})
public final class DomainExplorerTopComponent extends TopComponent {

    public static final String TC_NAME = "LegacyDomainExplorerTopComponent";
    public static final String TC_VERSION = "1.0";
    
    public static DomainExplorerTopComponent getInstance() {
        return (DomainExplorerTopComponent)WindowLocator.getByName(DomainExplorerTopComponent.TC_NAME);
    }

    public DomainExplorerTopComponent() {
        initComponents();
        setName(Bundle.CTL_LegacyDomainExplorerTopComponent());

        JTextArea area = new JTextArea("Please use Window->Reset Windows to update your display.");
        area.setLineWrap(true);
        area.setWrapStyleWord(true);
        add(area);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void componentOpened() {
    }

    @Override
    public void componentClosed() {
    }
    
    @Override
    protected void componentActivated() {
    }
    
    @Override
    protected void componentDeactivated() {
    }

    void writeProperties(java.util.Properties p) {
    }
    
    void readProperties(java.util.Properties p) {
    }
    
}
